name: CI w/ pytest-regsmart RTP only

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
    - main
    - 'mut-*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGSMART_PACKAGE: "git+https://github.com/leticosta4/pytest-regsmart@9bf18024382d2e910a4a81ae7330fdc527728da2"

jobs:
    test-regsmart-nr:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                include:
                    - python-version: "3.12"
                      channel-priority: "strict"
                      envfile: ".github/environment-ci.yml"

        steps:
        - uses: actions/checkout@v7
          with:
            fetch-depth: 0

        - name: Setup Miniforge
          uses: conda-incubator/setup-miniconda@v4
          with:
            miniforge-version: latest
            activate-environment: test
            conda-remove-defaults: true
            channel-priority: ${{ matrix.channel-priority }}
            python-version: ${{ matrix.python-version }}

        - name: Get Date
          id: get-date
          run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
          shell: bash

        - name: Cache Conda env
          uses: actions/cache@v6
          with:
            path: ${{ env.CONDA }}/envs
            key:
              conda-${{ runner.os }}--${{ runner.arch }}--${{
              steps.get-date.outputs.today }}-${{ env.CACHE_NUMBER
              }}-${{ matrix.python-version }}-${{ hashFiles( matrix.envfile ) }}
          env:
            CACHE_NUMBER: 0
          id: cache

        - name: Update environment
          run:
            conda env update -n test -f ${{ matrix.envfile }}
          if: steps.cache.outputs.cache-hit != 'true'

        - name: Conda info
          shell: bash -l {0}
          run: |
            conda info -a
            conda list
            python -c "import scipy; scipy.show_config()"

        - name: Install librosa
          shell: bash -l {0}
          run: python -m pip install --upgrade-strategy only-if-needed -e .[tests]

        - name: Install pytest-regsmart
          shell: bash -l {0}
          run: |
            python -m pip install "$REGSMART_PACKAGE"
            python -m pip freeze

        - name: Run pytest
          shell: bash -l {0}
          run: pytest --regsmart --no-rank --mpl-results-path=mpl_image_results/

        - name: Prepare artifact directory structure
          if: failure() && hashFiles('mpl_image_results/**') != ''
          id: prep_artifact
          run: |
            PR_NUM="${{ github.event.pull_request.number || github.run_id }}"
            ART_NAME="mpl-test-results-${{ runner.os }}--${{ runner.arch }}--${{ matrix.python-version }}-PR${PR_NUM}"

            mkdir -p "_artifact_stage/$ART_NAME"
            mv mpl_image_results/* "_artifact_stage/$ART_NAME/"

            echo "art_name=$ART_NAME" >> "$GITHUB_OUTPUT"

        - name: Upload image comparison failures if any
          if: failure() && steps.prep_artifact.outputs.art_name != ''
          uses: actions/upload-artifact@v7
          with:
            name: ${{ steps.prep_artifact.outputs.art_name }}
            path: _artifact_stage/
            retention-days: 7
            compression-level: 0
            overwrite: true
